apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: currencyservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
        - name: currencyservice
          image: 'softtekcoeapisms/currencyservice:1.0'
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  labels:
    name: currencyservice
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: currencyservice
  type: LoadBalancer